name: Deploy react app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: pnpm

      - name: install packages
        run: pnpm install

      - name: registry github user
        run: |
          git config --global user.email "jalesgervazzi@gmail.com"
          git config --global user.name "JoseAle2610"

      - name: deploy the app
        run: |
          git remote set-url origin https://git:${GH_TOKEN}@github.com/JoseAle2610/JoseAle2610.github.io.git
          pnpm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
